services:
  frontend:
    build:
      context: ./src/frontend/cupcake-dias-ui
      dockerfile: Dockerfile
    ports:
      - "7988:80"
    networks:
      - app-network

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "7989:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=${MYSQL_CONNECTION_STRING}
      - SMTP__PASSWORD=${SMTP_PASSWORD}
      - JWT__SECRET=${JWT_SECRET_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
